### ISSUE TITLE
GeneratedPluginRegistrant.java:24: error: cannot find symbol

### ISSUE THREAD

**Issue by Mahdijamebozorg** [miguelpruivo/flutter_file_picker#2063]
Flutter Channel stable, 3.44.1
file_picker: ^11.0.2
    
gradle-9.1.0-all
id("com.android.application") version "9.0.1" apply false    
id("org.jetbrains.kotlin.android") version "2.3.20" apply false

I tried version 10.3.10 with the same config and it worked, but when I upgraded to 11.0.2 I have the following error:

flutter build apk 
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
WARNING: Your app uses the following plugins that apply Kotlin Gradle Plugin (KGP): file_picker
Future versions of Flutter will fail to build if your app uses plugins that apply KGP.

Please check the changelogs of these plugins and upgrade to a version that supports Built-in Kotlin.
If no such version exists, report the issue to the plugin. If necessary, here is a guide on filing 
an issue against a plugin: https://docs.flutter.dev/release/breaking-changes/migrate-to-built-in-kotlin/for-app-developers#report-incompatible-kotlin-gradle-plugin-usage-to-plugin-authors

If you are a plugin author, please migrate your plugin to Built-in Kotlin using this guide: https://docs.flutter.dev/release/breaking-changes/migrate-to-built-in-kotlin/for-plugin-authors
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
D:\Programming\Flutter\Projects\my_local_ai\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java:24: error: cannot find symbol
      flutterEngine.getPlugins().add(new com.mr.flutter.plugin.filepicker.FilePickerPlugin());
                                                                         ^
  symbol:   class FilePickerPlugin
  location: package com.mr.flutter.plugin.filepicker
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler output below.
  D:\Programming\Flutter\Projects\my_local_ai\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java:24: error: cannot find symbol
        flutterEngine.getPlugins().add(new com.mr.flutter.plugin.filepicker.FilePickerPlugin());
                                                                           ^
    symbol:   class FilePickerPlugin
    location: package com.mr.flutter.plugin.filepicker
  1 error

* Try:
> Check your code and dependencies to fix the compilation error(s)
> Run with --scan to generate a Build Scan (Powered by Develocity).

BUILD FAILED in 20s
Running Gradle task 'assembleRelease'...                           21.2s
Gradle task assembleRelease failed with exit code 1

------------------------
flutter doctor
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.44.1, on Microsoft Windows [Version 10.0.19045.6466], locale en-US)
[√] Windows Version (10 Pro 64-bit, 22H2, 2009)
[√] Android toolchain - develop for Android devices (Android SDK version 36.0.0)
[√] Chrome - develop for the web
[√] Connected device (3 available)
[√] Network resources

**Comment by daniJimen** [comment]
@Mahdijamebozorg  you are not in latest version, 12.0.0-beta.5, in that version, its working fine, the warning that you see its a dependency of a flutter library that needs to update to AGP 9, nothing critical: 

<img width="1664" height="225" alt="Image" src="https://github.com/user-attachments/assets/e4793881-0252-4146-b310-3a9af0d659d5" />

<img width="277" height="163" alt="Image" src="https://github.com/user-attachments/assets/c0943a81-5d63-416e-ad0a-bfc4221b0e56" />

check it and please, confirm that your app can generate the apk succesfully

**Comment by Mahdijamebozorg** [comment]
@daniJimen Thank you, the version 11.0.2  is the latest version on pub.dev, I'll try your beta version from GitHub.

**Comment by RageshAntony** [comment]
@daniJimen 

I get this issue after upgrading to 12.0.0-beta.5,

```
  /// Pick a location for saving
  Future<String?> pickSaveLocation({
    String? suggestedName,
    String? initialDirectory,
  }) async {
    try {

      final result = await FilePicker.saveFile(
        fileName: suggestedName ?? 'database.kdb',
        type: FileType.custom,
        allowedExtensions: ['kdb'],
      );

      return result;
    } catch (e) {
      throw FileDataSourceException('Failed to pick save location: $e');
    }
  }
```

`The named parameter 'bytes' is required, but there's no corresponding argument. `

How to provide that 'bytes' ?

**Comment by linuswagner** [comment]
I faced the same problem on `11.0.2`. Updating to `12.0.0-beta.5` solved my problem

**Comment by daniJimen** [comment]
> [@daniJimen](https://github.com/daniJimen)
> 
> I get this issue after upgrading to 12.0.0-beta.5,
> 
> ```
>   /// Pick a location for saving
>   Future<String?> pickSaveLocation({
>     String? suggestedName,
>     String? initialDirectory,
>   }) async {
>     try {
> 
>       final result = await FilePicker.saveFile(
>         fileName: suggestedName ?? 'database.kdb',
>         type: FileType.custom,
>         allowedExtensions: ['kdb'],
>       );
> 
>       return result;
>     } catch (e) {
>       throw FileDataSourceException('Failed to pick save location: $e');
>     }
>   }
> ```
> 
> `The named parameter 'bytes' is required, but there's no corresponding argument. `
> 
> How to provide that 'bytes' ?

the bytes of the file picked, you can extract them from the platformfile that you get in pickfile method

**Comment by daniJimen** [comment]
@vicajilau  @navaronbracke please, close that task when you have time, thanks

**Comment by perissf1** [comment]
> [@Mahdijamebozorg](https://github.com/Mahdijamebozorg) you are not in latest version, 12.0.0-beta.5, in that version, its working fine, the warning that you see its a dependency of a flutter library that needs to update to AGP 9, nothing critical:
> 
> <img alt="Image" width="1664" height="225" src="https://private-user-images.githubusercontent.com/122808735/602647047-e4793881-0252-4146-b310-3a9af0d659d5.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3ODEwMjg1ODksIm5iZiI6MTc4MTAyODI4OSwicGF0aCI6Ii8xMjI4MDg3MzUvNjAyNjQ3MDQ3LWU0NzkzODgxLTAyNTItNDE0Ni1iMzEwLTNhOWFmMGQ2NTlkNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwNjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDYwOVQxODA0NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZjQzNmM2Zjc0ZTI2ZDIyYjQ1MmNjNmMzMDQzMDQxMzVlMmY5YTNhYzU5NGNmYWZlMTQ4NTRjOTM0M2U1ODk1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZyZXNwb25zZS1jb250ZW50LXR5cGU9aW1hZ2UlMkZwbmcifQ.XSJz5HYGlwF3t5wqR29m2RxnmAEGr1wnkn9IDdXKh3w"> <img alt="Image" width="277" height="163" src="https://private-user-images.githubusercontent.com/122808735/602647879-c0943a81-5d63-416e-ad0a-bfc4221b0e56.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3ODEwMjg1ODksIm5iZiI6MTc4MTAyODI4OSwicGF0aCI6Ii8xMjI4MDg3MzUvNjAyNjQ3ODc5LWMwOTQzYTgxLTVkNjMtNDE2ZS1hZDBhLWJmYzQyMjFiMGU1Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwNjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDYwOVQxODA0NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MDY0NDdkNmVkZmVhNGEzMzI0YTQwZTE5MmU1MmFlMzBmZGQ5MThmZGUxNWIxYWNmMzI3NWJlMDhmMzg3ZWM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZyZXNwb25zZS1jb250ZW50LXR5cGU9aW1hZ2UlMkZwbmcifQ.XlhXognRYAEnoyFRUM2TQKcSSVrUKkq-ZpTuUkq0gbI">
> check it and please, confirm that your app can generate the apk succesfully

That wasn't a warning, it was an error, which appears to be fixed in the beta version. However the same error was apparently fixed some months ago, but in the stable version it's still there.

**Comment by user97116** [comment]
same issue with filepicker 12.0.0-beta.5

**Comment by daniJimen** [comment]
> > [@daniJimen](https://github.com/daniJimen)
> > I get this issue after upgrading to 12.0.0-beta.5,
> > ```
> >   /// Pick a location for saving
> >   Future<String?> pickSaveLocation({
> >     String? suggestedName,
> >     String? initialDirectory,
> >   }) async {
> >     try {
> > 
> >       final result = await FilePicker.saveFile(
> >         fileName: suggestedName ?? 'database.kdb',
> >         type: FileType.custom,
> >         allowedExtensions: ['kdb'],
> >       );
> > 
> >       return result;
> >     } catch (e) {
> >       throw FileDataSourceException('Failed to pick save location: $e');
> >     }
> >   }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > `The named parameter 'bytes' is required, but there's no corresponding argument. `
> > How to provide that 'bytes' ?
> 
> the bytes of the file picked, you can extract them from the platformfile that you get in pickfile method

The bytes are provided by the pickFile function, which returns a PlatformFile. You can obtain the file bytes using the readAsBytes() function.
However, we are currently working on the next version to make the process more efficient. It will allow handling saved files either by their path or by their bytes. If you manage the file using its path (which will be also provided by PlatformFile), you won’t need to read the file bytes — you’ll only need to pass the path to the save file function.

that,s the PR: https://github.com/miguelpruivo/flutter_file_picker/pull/2059

**Comment by daniJimen** [comment]
> same issue with filepicker 12.0.0-beta.5

@user97116  Could you please send the logs you have and run a flutter doctor?
It’s a bit strange because in the latest beta version, it’s working fine on my side.

<img width="1677" height="95" alt="Image" src="https://github.com/user-attachments/assets/5661cd55-9bfc-41eb-bebf-d3f92a365d5a" />

Which Android version are you testing on?

**Comment by RageshAntony** [comment]
> > [@daniJimen](https://github.com/daniJimen)
> > I get this issue after upgrading to 12.0.0-beta.5,
> > ```
> >   /// Pick a location for saving
> >   Future<String?> pickSaveLocation({
> >     String? suggestedName,
> >     String? initialDirectory,
> >   }) async {
> >     try {
> > 
> >       final result = await FilePicker.saveFile(
> >         fileName: suggestedName ?? 'database.kdb',
> >         type: FileType.custom,
> >         allowedExtensions: ['kdb'],
> >       );
> > 
> >       return result;
> >     } catch (e) {
> >       throw FileDataSourceException('Failed to pick save location: $e');
> >     }
> >   }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > `The named parameter 'bytes' is required, but there's no corresponding argument. `
> > How to provide that 'bytes' ?
> 
> the bytes of the file picked, you can extract them from the platformfile that you get in pickfile method

How to create a new file with a given name? 

I need to open the file picker, navigate and show the location for a new file .

**Comment by daniJimen** [comment]
@RageshAntony looks the example of the library, you have an example here, firstly, you need to use method pickfile to select your file, that returns you a platformfile, that file have a method called readAsBytes(), that give you the bytes to send them to savefile method, anyways, in next version, you could choose doing the save file for that method, or only sending the path to savefile, but you need to wait to nextversion to use only path without get the bytes for the selected file

**Comment by RageshAntony** [comment]
@daniJimen 

> you need to use method pickfile to select your file, that returns you a platformfile

How to enter the file name for a new file that not yet created and needs to be created from the app itself ?

This function opens like this:

```
    final result = await FilePicker.pickFile(
      dialogTitle: 'Save new KDB file',
     // fileName: 'passwords.kdb',
      type: FileType.any,
    );
```

<img width="1344" height="2992" alt="Image" src="https://github.com/user-attachments/assets/8699830e-f235-4393-a317-0cb91ffa1829" />

The 11.0 version produces this build error in the parent post. That's why I am using this 12.0.0-beta.5.

**Comment by daniJimen** [comment]
@RageshAntony that new name needs to be sended into savefile, not in pickfile, please, review the example of library, you have here an example of the process
