### ISSUE TITLE
Android compile error registrar 

### ISSUE THREAD

**Issue by abdelaziz-mahdy** [miguelpruivo/flutter_file_picker#1643]
**Describe the bug**
After upgrading to flutter 3.27 the code fails to compile on android , using `flutter build apk`

**Platform**

- [x] Android
- [ ] iOS
- [ ] Web
- [ ] Desktop

**Platform OS version**
What version did it happen?

**How are you picking?**
```
Please, post the snippet here
```

**Details to reproduce the issue**
Provide all the details to reproduce the issue.

**Error Log**
```
/Users/AbdelazizMahdy/.pub-cache/hosted/pub.dev/file_picker-8.1.5/android/src/main/java/com/mr/flutter/plugin/filepicker/FilePickerPlugin.java:257: error: cannot find symbol
        if (registrar != null) {
            ^
  symbol:   variable registrar
  location: class FilePickerPlugin
/Users/AbdelazizMahdy/.pub-cache/hosted/pub.dev/file_picker-8.1.5/android/src/main/java/com/mr/flutter/plugin/filepicker/FilePickerPlugin.java:260: error: cannot find symbol
            registrar.addActivityResultListener(this.delegate);
            ^
  symbol:   variable registrar
  location: class FilePickerPlugin
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':file_picker:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

**Screenshots and/or video**
If applicable, add screenshots or video to help explain your problem.

**Flutter Version details**
```
[✓] Flutter (Channel stable, 3.27.0, on macOS 15.1.1 24B91 darwin-arm64, locale
    en-EG)
    • Flutter version 3.27.0 on channel stable at
      /Users/AbdelazizMahdy/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 8495dee1fd (25 hours ago), 2024-12-10 14:23:39 -0800
    • Engine revision 83bacfc525
    • Dart version 3.6.0
    • DevTools version 2.40.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/AbdelazizMahdy/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16B40
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.11+0-17.0.11b1207.24-11852314)

[✓] IntelliJ IDEA Community Edition (version 2024.2.0.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 242.20629

[✓] VS Code (version 1.95.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.102.0

[✓] Connected device (3 available)
    • macOS (desktop)                 • macos                 • darwin-arm64   •
      macOS 15.1.1 24B91 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         •
      macOS 15.1.1 24B91 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript •
      Google Chrome 131.0.6778.109

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```
**Additional context**

**Comment by DennisKragekjaer** [comment]
same here

**Comment by abdelaziz-mahdy** [comment]
just tested on the master branch got the same error so its in the package itself 
```

You are applying Flutter's main Gradle plugin imperatively using the apply script method, which is deprecated and will be removed in a future release. Migrate to applying Gradle plugins with the declarative plugins block: https://flutter.dev/to/flutter-gradle-plugin-apply

Font asset "MaterialIcons-Regular.otf" was tree-shaken, reducing it from 1645184 to 2180 bytes (99.9% reduction). Tree-shaking can be disabled by providing the --no-tree-shake-icons flag when building your app.
/Users/AbdelazizMahdy/flutter_projects/flutter_file_picker/android/src/main/java/com/mr/flutter/plugin/filepicker/FilePickerPlugin.java:257: error: cannot find symbol
        if (registrar != null) {
            ^
  symbol:   variable registrar
  location: class FilePickerPlugin
/Users/AbdelazizMahdy/flutter_projects/flutter_file_picker/android/src/main/java/com/mr/flutter/plugin/filepicker/FilePickerPlugin.java:260: error: cannot find symbol
            registrar.addActivityResultListener(this.delegate);
            ^
  symbol:   variable registrar
  location: class FilePickerPlugin
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':file_picker:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 45s
Running Gradle task 'assembleRelease'...                           46.7s
Gradle task assembleRelease failed with exit code 1
AbdelazizMahdy@abdelazizs-MacBook-Pro example % 
```

**Comment by millerf** [comment]
Same with gradle 7.5

```
 compileSdkVersion = 34                // or higher / as desired
        targetSdkVersion = 34                // or higher / as desired
        minSdkVersion = 23                // Required minimum
        appCompatVersion = "1.4.2"           // or higher / as desired
        playServicesLocationVersion = "21.0.1"  // or higher / as de
```

**Comment by abdelaziz-mahdy** [comment]
for anyone who is having the issue you can use my branch until the pr gets merged
```
dependency_overrides: 
  file_picker:
    git:
      url: https://github.com/abdelaziz-mahdy/flutter_file_picker
      ref: fix-flutter-3.27-compile-error
```

**Comment by ddxl123** [comment]
same

**Comment by ekuleshov** [comment]
Oddly. Reverting to `file_picker: 8.1.4` makes it compile with Flutter 3.27

**Comment by abdelaziz-mahdy** [comment]
actually yes it was removed before looks like a commit brought it back 
https://github.com/miguelpruivo/flutter_file_picker/commit/7c5ff40ed3dab46678017395b9d03d3ae88912dc this the removal one

**Comment by mohsinnaqvi606** [comment]
same issue. even after downgrading to the last working version i.e `file_picker: ^8.1.4` issue is not going

**Comment by ekuleshov** [comment]
> same issue. even after downgrading to the last working version i.e `file_picker: ^8.1.4` issue is not going

You need to use exact version. Not the open ended with `^`

**Comment by mohsinnaqvi606** [comment]
> > same issue. even after downgrading to the last working version i.e `file_picker: ^8.1.4` issue is not going
> 
> You need to use exact version. Not the open ended with `^`

@ekuleshov It worked for me, thanks.

**Comment by fadelfffar** [comment]
same issue here

**Comment by Crucialjun** [comment]
Just got this issue

**Comment by kiyo9w** [comment]
same issue here, thanks for your solution

**Comment by AdelDaniel** [comment]
The error exists in the new version `file_picker: ^8.1.5` 

So I changed the version to be `file_picker: 8.1.4` downgrade and remove `^` and it works

**Comment by kjxbyz** [comment]
Same with gradle 8.11.1

```
compileSdkVersion = 34
targetSdkVersion = 34
minSdkVersion = 24
```

**Comment by krll-kov** [comment]
Same

**Comment by neo11235** [comment]
same issue here, happened after running pub upgrade, now reverted back to version 8.1.3 and working fine

**Comment by muhsinPlanetMedia** [comment]
same

**Comment by SherwinDeveloper** [comment]
same

**Comment by MisaGu** [comment]
same

**Comment by rjahn** [comment]
same problem with 3.24.3 or 3.24.5

**Comment by Joao6** [comment]
same here

**Comment by diegodulval** [comment]
same here

**Comment by jaimecalderon19** [comment]
I did the same thing with a flutter clean and then a flutter pub get and it stopped working.

**Comment by tototo23** [comment]
Same issue here...

**Comment by Katletos** [comment]
same, `8.1.4` helped

**Comment by a1573595** [comment]
Using Flutter SDK 3.24.5 with file_picket 8.1.5 has the same problem.

**Comment by JackCui001** [comment]
Still can reproduce this problem on Flutter 3.24.5.

**Comment by wanby** [comment]
Change to `file_picker: 8.1.4` can help on Flutter 3.24.3, Android 34.

**Comment by omair-audviklabs** [comment]
> for anyone who is having the issue you can use my branch until the pr gets merged
> 
> ```
> dependency_overrides: 
>   file_picker:
>     git:
>       url: https://github.com/abdelaziz-mahdy/flutter_file_picker
>       ref: fix-flutter-3.27-compile-error
> ```

No matter whatever flutter version you have, flutter pub cache will have file picker 8.1.5 even if you use older versions of file picker package. So it always shows the error. To resolve it, adding this dependency override only helped me.

**Comment by omairsadiq** [comment]
> for anyone who is having the issue you can use my branch until the pr gets merged
> 
> ```
> dependency_overrides: 
>   file_picker:
>     git:
>       url: https://github.com/abdelaziz-mahdy/flutter_file_picker
>       ref: fix-flutter-3.27-compile-error
> ```

No matter whatever flutter version you have, flutter pub cache will have file picker 8.1.5 even if you use older versions of file picker package. So it always shows the error. To resolve it, adding this dependency override only helped me. Hope, the dev of file_picker releases a fix for it very soon. Fingers crossed.

**Comment by ksmohamed** [comment]
same issues

**Comment by SirDank** [comment]
same issue here

**Comment by richanshah** [comment]
same issue

**Comment by richanshah** [comment]
> Oddly. Reverting to `file_picker: 8.1.4` makes it compile with Flutter 3.27

this works

**Comment by imrajdev** [comment]
> Oddly. Reverting to `file_picker: 8.1.4` makes it compile with Flutter 3.27

Its worked! Thanks ❤️

**Comment by rzimanTJY** [comment]
Same issue here. Reverting to 8.1.4 solved for now

**Comment by deakjahn** [comment]
@omairsadiq "No matter whatever flutter version you have, flutter pub cache will have file picker 8.1.5 even if you use older versions of file picker package."

This is, actually, not true. You have to remove the ^ designator from your pubspec. ^ means "this version or later compatible". If you specifiy 8.1.4 without the ^, you'll get exactly that and nothing else.

**Comment by sim8962** [comment]
thanks issue fixed  with:( file_picker : 8.1.4) without ^ instead of (file_picker: ^8.1.5) last version

**Comment by dawid-niedzwiecki** [comment]
same issue

**Comment by rjahn** [comment]
It's not necessary to comment every success here, because it's clear that 8.1.4 is working. It didn't contain the "problem".
It's a long issue for such a simple problem/fix and doesn't make it easier to read. Let's wait for an update 😉

**Comment by mauriziopinotti** [comment]
> It's not necessary to comment every success here, because it's clear that 8.1.4 is working. It didn't contain the "problem". It's a long issue for such a simple problem/fix and doesn't make it easier to read. Let's wait for an update 😉

And it's not necessary to say "same here" too :dagger: 
Every reply is a bunch of emails sent to all subscribers and only increases the carbon-footprint of my day. 
Please react with a thumb-up to the post rather than commenting!

**Comment by troller2017** [comment]
same same issue.

**Comment by MODE83-PROJET-DEV** [comment]
same same issue, work in 8.1.4 is ok :)

**Comment by alessandromrt** [comment]
Same here

**Comment by RanaUsama20** [comment]
> Oddly. Reverting to `file_picker: 8.1.4` makes it compile with Flutter 3.27

it worked, thanks!! do you know what is the difference between 8.1.4 and ^8.1.4 tho?

**Comment by richanshah** [comment]
> **Describe the bug** After upgrading to flutter 3.27 the code fails to compile on android , using `flutter build apk`
> 
> **Platform**
> 
> * [x]  Android
> * [ ]  iOS
> * [ ]  Web
> * [ ]  Desktop
> 
> **Platform OS version** What version did it happen?
> 
> **How are you picking?**
> 
> ```
> Please, post the snippet here
> ```
> 
> **Details to reproduce the issue** Provide all the details to reproduce the issue.
> 
> **Error Log**
> 
> ```
> /Users/AbdelazizMahdy/.pub-cache/hosted/pub.dev/file_picker-8.1.5/android/src/main/java/com/mr/flutter/plugin/filepicker/FilePickerPlugin.java:257: error: cannot find symbol
>         if (registrar != null) {
>             ^
>   symbol:   variable registrar
>   location: class FilePickerPlugin
> /Users/AbdelazizMahdy/.pub-cache/hosted/pub.dev/file_picker-8.1.5/android/src/main/java/com/mr/flutter/plugin/filepicker/FilePickerPlugin.java:260: error: cannot find symbol
>             registrar.addActivityResultListener(this.delegate);
>             ^
>   symbol:   variable registrar
>   location: class FilePickerPlugin
> 2 errors
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':file_picker:compileReleaseJavaWithJavac'.
> > Compilation failed; see the compiler error output for details.
> ```
> 
> **Screenshots and/or video** If applicable, add screenshots or video to help explain your problem.
> 
> **Flutter Version details**
> 
> ```
> [✓] Flutter (Channel stable, 3.27.0, on macOS 15.1.1 24B91 darwin-arm64, locale
>     en-EG)
>     • Flutter version 3.27.0 on channel stable at
>       /Users/AbdelazizMahdy/Developer/flutter
>     • Upstream repository https://github.com/flutter/flutter.git
>     • Framework revision 8495dee1fd (25 hours ago), 2024-12-10 14:23:39 -0800
>     • Engine revision 83bacfc525
>     • Dart version 3.6.0
>     • DevTools version 2.40.2
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
>     • Android SDK at /Users/AbdelazizMahdy/Library/Android/sdk
>     • Platform android-34, build-tools 34.0.0
>     • Java binary at: /Applications/Android
>       Studio.app/Contents/jbr/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build
>       17.0.11+0-17.0.11b1207.24-11852314)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 16.1)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Build 16B40
>     • CocoaPods version 1.16.2
> 
> [✓] Chrome - develop for the web
>     • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
> 
> [✓] Android Studio (version 2024.1)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build
>       17.0.11+0-17.0.11b1207.24-11852314)
> 
> [✓] IntelliJ IDEA Community Edition (version 2024.2.0.2)
>     • IntelliJ at /Applications/IntelliJ IDEA CE.app
>     • Flutter plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin version 242.20629
> 
> [✓] VS Code (version 1.95.3)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 3.102.0
> 
> [✓] Connected device (3 available)
>     • macOS (desktop)                 • macos                 • darwin-arm64   •
>       macOS 15.1.1 24B91 darwin-arm64
>     • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         •
>       macOS 15.1.1 24B91 darwin-arm64
>     • Chrome (web)                    • chrome                • web-javascript •
>       Google Chrome 131.0.6778.109
> 
> [✓] Network resources
>     • All expected network resources are available.
> 
> • No issues found!
> ```
> 
> **Additional context** Add any other context about the problem here.

please close the issue, too many unnecessary comments coming.

**Comment by deakjahn** [comment]
@RanaUsama20 Yes. `^some-version` means "some version or newer" (provided it's compatible). That's why it doesn't help you here, if you forget removing the caret, you'll get the newer version automatically.

**Comment by abdelaziz-mahdy** [comment]
> > **Describe the bug** After upgrading to flutter 3.27 the code fails to compile on android , using `flutter build apk`
> > 
> > **Platform**
> > 
> > * [x]  Android
> > * [ ]  iOS
> > * [ ]  Web
> > * [ ]  Desktop
> > 
> > **Platform OS version** What version did it happen?
> > 
> > **How are you picking?**
> > 
> > ```
> > Please, post the snippet here
> > ```
> > 
> > **Details to reproduce the issue** Provide all the details to reproduce the issue.
> > 
> > **Error Log**
> > 
> > ```
> > /Users/AbdelazizMahdy/.pub-cache/hosted/pub.dev/file_picker-8.1.5/android/src/main/java/com/mr/flutter/plugin/filepicker/FilePickerPlugin.java:257: error: cannot find symbol
> >         if (registrar != null) {
> >             ^
> >   symbol:   variable registrar
> >   location: class FilePickerPlugin
> > /Users/AbdelazizMahdy/.pub-cache/hosted/pub.dev/file_picker-8.1.5/android/src/main/java/com/mr/flutter/plugin/filepicker/FilePickerPlugin.java:260: error: cannot find symbol
> >             registrar.addActivityResultListener(this.delegate);
> >             ^
> >   symbol:   variable registrar
> >   location: class FilePickerPlugin
> > 2 errors
> > 
> > FAILURE: Build failed with an exception.
> > 
> > * What went wrong:
> > Execution failed for task ':file_picker:compileReleaseJavaWithJavac'.
> > > Compilation failed; see the compiler error output for details.
> > ```
> > 
> > **Screenshots and/or video** If applicable, add screenshots or video to help explain your problem.
> > 
> > **Flutter Version details**
> > 
> > ```
> > [✓] Flutter (Channel stable, 3.27.0, on macOS 15.1.1 24B91 darwin-arm64, locale
> >     en-EG)
> >     • Flutter version 3.27.0 on channel stable at
> >       /Users/AbdelazizMahdy/Developer/flutter
> >     • Upstream repository https://github.com/flutter/flutter.git
> >     • Framework revision 8495dee1fd (25 hours ago), 2024-12-10 14:23:39 -0800
> >     • Engine revision 83bacfc525
> >     • Dart version 3.6.0
> >     • DevTools version 2.40.2
> > 
> > [✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
> >     • Android SDK at /Users/AbdelazizMahdy/Library/Android/sdk
> >     • Platform android-34, build-tools 34.0.0
> >     • Java binary at: /Applications/Android
> >       Studio.app/Contents/jbr/Contents/Home/bin/java
> >     • Java version OpenJDK Runtime Environment (build
> >       17.0.11+0-17.0.11b1207.24-11852314)
> >     • All Android licenses accepted.
> > 
> > [✓] Xcode - develop for iOS and macOS (Xcode 16.1)
> >     • Xcode at /Applications/Xcode.app/Contents/Developer
> >     • Build 16B40
> >     • CocoaPods version 1.16.2
> > 
> > [✓] Chrome - develop for the web
> >     • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
> > 
> > [✓] Android Studio (version 2024.1)
> >     • Android Studio at /Applications/Android Studio.app/Contents
> >     • Flutter plugin can be installed from:
> >       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
> >     • Dart plugin can be installed from:
> >       🔨 https://plugins.jetbrains.com/plugin/6351-dart
> >     • Java version OpenJDK Runtime Environment (build
> >       17.0.11+0-17.0.11b1207.24-11852314)
> > 
> > [✓] IntelliJ IDEA Community Edition (version 2024.2.0.2)
> >     • IntelliJ at /Applications/IntelliJ IDEA CE.app
> >     • Flutter plugin can be installed from:
> >       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
> >     • Dart plugin version 242.20629
> > 
> > [✓] VS Code (version 1.95.3)
> >     • VS Code at /Applications/Visual Studio Code.app/Contents
> >     • Flutter extension version 3.102.0
> > 
> > [✓] Connected device (3 available)
> >     • macOS (desktop)                 • macos                 • darwin-arm64   •
> >       macOS 15.1.1 24B91 darwin-arm64
> >     • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         •
> >       macOS 15.1.1 24B91 darwin-arm64
> >     • Chrome (web)                    • chrome                • web-javascript •
> >       Google Chrome 131.0.6778.109
> > 
> > [✓] Network resources
> >     • All expected network resources are available.
> > 
> > • No issues found!
> > ```
> > 
> > **Additional context** Add any other context about the problem here.
> 
> please close the issue, too many unnecessary comments coming.

I don't have a way to limit the comments, and people have mentioned that each one commenting on the same problem or the same fix doesn't help, but people do it anyway 


I hope the package maintainer merges the pr so we can close this as completed 

Note: even if I close the issue it won't limit the comments 😅 and won't solve the issue so that's not a solution 


As a lot of people mentioned 

Reverting to file_picker: 8.1.4 fixes the issue, or using my branch as you can find at a comment above


For newcomers please read the fixes provided above before adding any more comments

**Comment by dong336** [comment]
I'm Flutter 3.24.5, It's resolved by using 8.1.4.

**Comment by SaurabhAlex** [comment]
If you're facing build errors related to file_picker or Java/Kotlin version mismatches, here's a solution that worked for me:

Step 1: Update file_picker Version
In your pubspec.yaml, downgrade file_picker to a compatible version:
file_picker: 8.1.4
(Remove the ^ symbol to avoid automatic updates.)

Step 2: Update build.gradle File
In android/app/build.gradle, replace the compileOptions block with this:
compileOptions {
    sourceCompatibility JavaVersion.VERSION_17
    targetCompatibility JavaVersion.VERSION_17
}
kotlinOptions {
    jvmTarget = "17"
}


Step 3: Update Gradle Wrapper
In android/gradle/wrapper/gradle-wrapper.properties, update the distributionUrl:
distributionUrl=https\://services.gradle.org/distributions/gradle-8.3-all.zip

(If you're using a different Gradle version, update 8.3 accordingly.)

Step 4: Update settings.gradle
In android/settings.gradle, adjust the plugin versions:
com.android.application → 8.1.0
org.jetbrains.kotlin.android → 1.8.22

After making these changes, run the following commands:
flutter clean
flutter pub get
flutter build apk

This resolved the issue for me. Let me know if it works for you too! 😊

**Comment by Icarus-conf** [comment]
Solution is to update your pubspec.yaml
file_picker: 8.1.4 
without ^

**Comment by FeodorFitsner** [comment]
I'm getting "registrar" error again with `file_picker: 8.1.5`. Regression?

**Comment by Zayha** [comment]
1) Add the version to pubspec.yaml: _file_picker: 8.1.4_ 
2) Clearing the cache: _dart pub cache clean_
3) Download the new dependency: _flutter pub get_
4) Profit! _flutter build apk --release_ without errors

**Comment by rufus-op** [comment]
you can use this repo i have fixed the issue

https://github.com/rufus-op/file_picker

replace 

  file_picker:  8.1.5
  
  with 
  
  file_picker:
    git:
      url: https://github.com/rufus-op/file_picker

**Comment by abdelaziz-mahdy** [comment]
> I don't have file_picker in app but still getting same issue
@AwaisQazii  you can override it like this comment since a package is using it in your app
https://github.com/miguelpruivo/flutter_file_picker/issues/1643#issuecomment-2537411088
or 
```
dependency_overrides: 
  file_picker: 8.1.4
```

**Comment by reidbaker** [comment]
My teammate on flutter removed v1 embeddings in this pr https://github.com/miguelpruivo/flutter_file_picker/pull/1527 fixing the issue we filed https://github.com/miguelpruivo/flutter_file_picker/issues/1526. 

Is appears that in pull request [#1453](https://github.com/miguelpruivo/flutter_file_picker/pull/1453/files#diff-a28f06c7f47e384adf16f883f6bd99eae4cabc9c10f532d8fe0eee8c33a9ce00)  the lines we removed were added back in. 

5 days ago flutter released 3.27 which was the first stable release to not have the v1 embedding code so any user with this plugin and 3.27 would fail to compile. 

At first glance [this pr](https://github.com/miguelpruivo/flutter_file_picker/pull/1644) appears to address the regression.

**Comment by miguelpruivo** [comment]
Fixed with 8.1.6.

**Comment by YesThatGy** [comment]
> you can use this repo i have fixed the issue
> 
> https://github.com/rufus-op/file_picker
> 
> replace
> 
> file_picker: 8.1.5
>
> with
>
> file_picker: git: url: https://github.com/rufus-op/file_picker

Thank you! This worked a treat, until the official release settles

**Comment by RanaUsama20** [comment]
> @RanaUsama20 Yes. `^some-version` means "some version or newer" (provided it's compatible). That's why it doesn't help you here, if you forget removing the caret, you'll get the newer version automatically.

Thanks!!
