### ISSUE TITLE
Flutter 3.0.5 does not compile on file_picker 5.2.8

### ISSUE THREAD

**Issue by micaelcid** [miguelpruivo/flutter_file_picker#1260]
Currently, we're using Flutter 3.0.5 and as soon as we updated file_picker to 5.2.8, we started getting the following exception while compiling tests or compiling the app itself:
```
.pub-cache/hosted/pub.dartlang.org/file_picker-5.2.8/lib/src/platform_file.dart:53:9: Error: Type 'Uint8List' not found.
  final Uint8List? bytes;
        ^^^^^^^^^
.pub-cache/hosted/pub.dartlang.org/file_picker-5.2.8/lib/src/platform_file.dart:53:9: Error: 'Uint8List' isn't a type.
  final Uint8List? bytes;
```

After I manually downgraded this package back to 5.2.7, the compilation error disappeared.

By taking a glance over the change logs, I couldn't find what could cause this issue. Was this problem expected?

**Comment by mateusvtt** [comment]
Having the same issue here

**Comment by miguelslemos** [comment]
The issue is related to removed import here https://github.com/miguelpruivo/flutter_file_picker/commit/9d1d9efc3d70385b459d84adb431629f417a33f0#diff-38d8f870fecf77b1946a59ac5ed87e3eac24c8a86dc31ec3fd8970896cf8c016L2

**Comment by philenius** [comment]
Thank you @miguelslemos for identifying the problematic commit. Turns out, that blindly following the Linter's recommendations, can be dangerous. Sorry for the inconvenience. Will be fixed with `file_picker` 5.2.9.

**Comment by OutdatedGuy** [comment]
That's interesting, I checked `package:flutter/foundation.dart` exports and it does export `Uint8List` from the file `src/foundation/serialization.dart` as:

```dart
export 'dart:typed_data' show ByteData, Endian, Float32List, Float64List, Int32List, Int64List, Uint8List;
```

weird bug it seems.
