### ISSUE TITLE
Kotlin 2.1.0 compatibility issues in file_picker 10.3.3

### ISSUE THREAD

**Issue by jimmyff** [miguelpruivo/flutter_file_picker#1890]
## Bug Description
file_picker 10.3.3 fails to compile with Kotlin 2.1.0, showing multiple compilation errors related to missing FileInfo class and type inference issues.

## Environment
  - file_picker: 10.3.3
  - Kotlin: 2.1.0
  - Android Gradle Plugin: 8.13.0
  - Flutter: 3.35.3

## Error Messages
```
  e: Cannot infer type for this parameter. Please specify it explicitly.
  e: Unresolved reference 'FileInfo'.
  e: Not enough information to infer type argument for 'R'.
```

## Workaround
  Downgrading to Kotlin 1.9.24 resolves the compilation errors.

## Expected Behavior
  Plugin should compile successfully with Kotlin 2.1.0, as this is the recommended version for Android API 36 support.

**Comment by ddfreiling** [comment]
We have the same issue. Version 10.1.2 gives error about compile SDK, but version 10.3.3 gives these compilation errors like `Cannot infer type for this parameter. Specify it explicitly.` and `Unresolved reference 'FileInfo'.`

Please help fix this?

**Comment by philips77** [comment]
For me for some reason the issue was gone after moving to Kotlin 2.2.20.

**Comment by HeavySnowJakarta** [comment]
downgrade `file_picker` to 10.2.4 also helps as it may be harder to downgrade kotlin

**Comment by tucici** [comment]
> 降级`file_picker`到 10.2.4 也有帮助，因为降级 kotlin 可能会更困难

This worked for me

**Comment by navaronbracke** [comment]
Does this still apply with version 10.3.6 ?

**Comment by vicajilau** [comment]
@jimmyff  Do you have more information about this? Could you confirm if master branch has the same issue for you?
